---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dailyclean
  namespace: gthomas59800-dev
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - get
      - create
      - patch
      - update
      - delete
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dailyclean
  namespace: gthomas59800-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dailyclean
  namespace: gthomas59800-dev
subjects:
  - kind: ServiceAccount
    name: dailyclean
    namespace: gthomas59800-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dailyclean
---
